Python3 fix for encrypting (#1)
* Python3 fix for encrypting

I was getting
```
Traceback (most recent call last):
  File "../env/bin/kms-encryption", line 11, in <module>
    load_entry_point('kms-encryption-toolbox==0.0.10', 'console_scripts', 'kms-encryption')()
  File "../env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "../env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "../env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "../env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "../env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "../env/lib/python3.5/site-packages/kmsencryption/__main__.py", line 53, in encrypt
    click.echo(prefix + result)
TypeError: Can't convert 'bytes' object to str implicitly
```
where prefix is string and result is bytes.

* fix missing parenthesis

* Create setup.py